create database QuanLiKhachHang
 use QuanLiKhachHang

 CREATE TABLE SACH
 (
	MaSach CHAR(5) PRIMARY KEY NOT NULL,
	TenSach NVARCHAR(20),
	TheLoai	NVARCHAR(20),
	NXB NVARCHAR(20)
 )

 CREATE TABLE KHACHHANG
 (
	MaKH CHAR(5) PRIMARY KEY NOT NULL,
	Hoten NVARCHAR(25),
	NgaySinh SMALLDATETIME,
	DiaChi NVARCHAR(50),
	SoDT VARCHAR(15),
	NgDK SMALLDATETIME,
 )

 CREATE TABLE PHIEUMUA
 (
	MaPM CHAR(5) PRIMARY KEY NOT NULL,
	MaKH CHAR(5),
	NgayMua SMALLDATETIME,
	SoSachMua INT
 )

 ALTER TABLE PHIEUMUA ADD FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)  

 CREATE TABLE CHITIET_PHIEUMUA
 (
	MaSach CHAR(5) NOT NULL FOREIGN KEY REFERENCES SACH(MaSach),
	MaPM CHAR(5) NOT NULL FOREIGN KEY REFERENCES PHIEUMUA(MaPM),
	CONSTRAINT pk_ctpm PRIMARY KEY (MaSach,MaPM)
 )